
0:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: 'false'
  isRepeater: 'false'
  isRouter: 'false'
  neighborInfo: 'false'
  x: -63.567436
  y: 44.635978
  z: 1.0
1:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: 'false'
  isRepeater: 'false'
  isRouter: 'false'
  neighborInfo: 'false'
  x: -63.570757
  y: 44.640205
  z: 1.0
2:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: 'false'
  isRepeater: 'false'
  isRouter: 'false'
  neighborInfo: 'false'
  x: -63.575423
  y: 44.636207
  z: 1.0
3:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: 'false'
  isRepeater: 'false'
  isRouter: 'false'
  neighborInfo: 'false'
  x: -63.624615
  y: 44.662302
  z: 1.0
4:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: 'false'
  isRepeater: 'false'
  isRouter: 'false'
  neighborInfo: 'false'
  x: -63.606626
  y: 44.651866
  z: 1.0
